zalando/planb-provider

- src/main/java/org/zalando/planb/provider/ErrorResponse.java
- src/main/java/org/zalando/planb/provider/RestControllerAdvice.java
- src/test/java/org/zalando/planb/provider/ControllerAdviceDebugIT.java
- src/test/java/org/zalando/planb/provider/ControllerAdviceIT.java
- src/test/java/org/zalando/planb/provider/ErrorController.java
- src/test/java/org/zalando/planb/provider/PassThroughResponseErrorHandler.java
- src/test/resources/config/application-it-debug.yml
> first shot for rest-controller-advice

- src/main/java/org/zalando/planb/provider/ClientManagedRealm.java
- src/main/java/org/zalando/planb/provider/ClientRealm.java
- src/main/java/org/zalando/planb/provider/ClientRealmAuthenticationException.java
- src/main/java/org/zalando/planb/provider/ClientRealmAuthorizationException.java
- src/main/java/org/zalando/planb/provider/CustomerUserRealm.java
- src/main/java/org/zalando/planb/provider/Metric.java
- src/main/java/org/zalando/planb/provider/OIDCController.java
- src/main/java/org/zalando/planb/provider/RealmAuthenticationException.java
- src/main/java/org/zalando/planb/provider/RealmAuthorizationException.java
- src/main/java/org/zalando/planb/provider/RestException.java
- src/main/java/org/zalando/planb/provider/UserManagedRealm.java
- src/main/java/org/zalando/planb/provider/UserRealm.java
- src/main/java/org/zalando/planb/provider/UserRealmAuthenticationException.java
- src/main/java/org/zalando/planb/provider/UserRealmAuthorizationException.java
- src/test/java/org/zalando/planb/provider/MetricTest.java
- src/test/java/org/zalando/planb/provider/ServiceUserAuthenticationIT.java
this PR will provide additional metrics to get a more detailed view about the access token requests and JWT signing durations.
> More metrics

- pom.xml
- src/main/java/org/zalando/planb/provider/CassandraConfig.java
- src/main/java/org/zalando/planb/provider/CassandraProperties.java
- src/main/java/org/zalando/planb/provider/Main.java
- src/main/java/org/zalando/planb/provider/RealmNotManagedException.java
- src/test/resources/config/application-it.yml
> #20 added optional username + password to the cassandra properties

- src/main/java/org/zalando/planb/provider/CustomerUserRealm.java
- src/main/java/org/zalando/planb/provider/RestControllerAdvice.java
- src/test/java/org/zalando/planb/provider/CustomerUserRealmTest.java
> #26 masked customer email in error message

- src/main/java/org/zalando/planb/provider/ClientManagedRealm.java
- src/main/java/org/zalando/planb/provider/ClientRealm.java
- src/main/java/org/zalando/planb/provider/ClientRealmAuthorizationException.java
- src/main/java/org/zalando/planb/provider/CustomerUserRealm.java
- src/main/java/org/zalando/planb/provider/Main.java
- src/main/java/org/zalando/planb/provider/OIDCController.java
- src/main/java/org/zalando/planb/provider/RealmAuthorizationException.java
- src/main/java/org/zalando/planb/provider/ScopeProperties.java
- src/main/java/org/zalando/planb/provider/UserManagedRealm.java
- src/main/java/org/zalando/planb/provider/UserRealm.java
- src/main/java/org/zalando/planb/provider/UserRealmAuthorizationException.java
- src/test/java/org/zalando/planb/provider/CustomerUserRealmIT.java
- src/test/java/org/zalando/planb/provider/OIDCCreateTokenIT.java
- src/test/java/org/zalando/planb/provider/ScopePropertiesTest.java
- src/test/resources/config/application-it.yml
- src/test/resources/config/application-scopePropertiesTest.yml
> #25 default scopes, configurable per realm

- src/main/java/org/zalando/planb/provider/OIDCController.java
- src/main/java/org/zalando/planb/provider/RealmConfig.java
- src/main/java/org/zalando/planb/provider/ScopeProperties.java
- src/test/java/org/zalando/planb/provider/OIDCCreateTokenIT.java
- src/test/java/org/zalando/planb/provider/RealmConfigTest.java
> #24 find realm name in Host header (if param missing)

- src/main/java/org/zalando/planb/provider/BadRequestException.java
- src/main/java/org/zalando/planb/provider/ClientManagedRealm.java
- src/main/java/org/zalando/planb/provider/ClientRealmAuthenticationException.java
- src/main/java/org/zalando/planb/provider/ClientRealmAuthorizationException.java
- src/main/java/org/zalando/planb/provider/CustomerUserRealm.java
- src/main/java/org/zalando/planb/provider/InvalidInputException.java
- src/main/java/org/zalando/planb/provider/NotFoundException.java
- src/main/java/org/zalando/planb/provider/OIDCController.java
- src/main/java/org/zalando/planb/provider/RealmAuthenticationException.java
- src/main/java/org/zalando/planb/provider/RealmAuthorizationException.java
- src/main/java/org/zalando/planb/provider/RealmNotFoundException.java
- src/main/java/org/zalando/planb/provider/RealmNotManagedException.java
- src/main/java/org/zalando/planb/provider/RestControllerAdvice.java
- src/main/java/org/zalando/planb/provider/RestException.java
- src/main/java/org/zalando/planb/provider/UserManagedRealm.java
- src/main/java/org/zalando/planb/provider/UserRealmAuthenticationException.java
- src/main/java/org/zalando/planb/provider/UserRealmAuthorizationException.java
- src/test/java/org/zalando/planb/provider/OIDCCreateTokenIT.java
> #31 improved error messages (most according to RFC)

- pom.xml
- schema.cql
- scripts/generate-load-test-data.py
- src/main/java/org/zalando/planb/provider/CassandraUserRealm.java
- src/main/java/org/zalando/planb/provider/ClientController.java
- src/main/java/org/zalando/planb/provider/Realm.java
- src/main/java/org/zalando/planb/provider/UserController.java
- src/main/java/org/zalando/planb/provider/UserPasswordHash.java
- src/test/java/org/zalando/planb/provider/ClientControllerIT.java
- src/test/java/org/zalando/planb/provider/RealmTest.java
- src/test/java/org/zalando/planb/provider/ServiceUserAuthenticationIT.java
- src/test/java/org/zalando/planb/provider/UserControllerIT.java
- src/test/resources/testdata.cql
Fixes #34 
The auditing columns are not yet correctly filled, but this can be done in a later PR (having the schema changes in place and deployed is more important).
> 6 auditing columns

- src/main/java/org/zalando/planb/provider/CassandraClientRealm.java
- src/main/java/org/zalando/planb/provider/CassandraUserRealm.java
- src/main/java/org/zalando/planb/provider/ClientController.java
- src/main/java/org/zalando/planb/provider/ClientData.java
- src/main/java/org/zalando/planb/provider/ClientManagedRealm.java
- src/main/java/org/zalando/planb/provider/CurrentUser.java
- src/main/java/org/zalando/planb/provider/CurrentUserInSecurityContext.java
- src/main/java/org/zalando/planb/provider/UserController.java
- src/main/java/org/zalando/planb/provider/UserData.java
- src/main/java/org/zalando/planb/provider/UserManagedRealm.java
- src/main/java/org/zalando/planb/provider/UserPasswordHash.java
- src/test/java/org/zalando/planb/provider/AbstractSpringTest.java
- src/test/java/org/zalando/planb/provider/ClientControllerIT.java
- src/test/java/org/zalando/planb/provider/ServiceUserAuthenticationIT.java
- src/test/java/org/zalando/planb/provider/UserControllerIT.java
- src/test/java/org/zalando/planb/provider/UserPasswordHashTest.java
- src/test/resources/testdata.cql
> 6 fill auditing columns

- src/main/java/org/zalando/planb/provider/OIDCController.java
- src/test/java/org/zalando/planb/provider/ServiceUserAuthenticationIT.java
> #48 do not fail if client secret contains a colon

- pom.xml
- src/main/java/org/zalando/planb/provider/AuthorizeController.java
- src/main/java/org/zalando/planb/provider/Main.java
- src/main/java/org/zalando/planb/provider/OIDCController.java
- src/main/java/org/zalando/planb/provider/OIDCCreateTokenResponse.java
- src/main/java/org/zalando/planb/provider/RealmConfig.java
- src/main/java/org/zalando/planb/provider/RealmProperties.java
- src/main/java/org/zalando/planb/provider/ScopeProperties.java
- src/main/resources/config/application.yml
- src/test/java/org/zalando/planb/provider/AuthorizationCodeGrantFlowIT.java
- src/test/java/org/zalando/planb/provider/OIDCControllerTest.java
- src/test/java/org/zalando/planb/provider/OIDCCreateTokenIT.java
- src/test/java/org/zalando/planb/provider/RealmConfigTest.java
- src/test/java/org/zalando/planb/provider/RealmPropertiesTest.java
- src/test/java/org/zalando/planb/provider/ServiceUserAuthenticationIT.java
- src/test/resources/config/application-it.yml
- src/test/resources/testdata.cql
> 57 id token openid scope

- src/main/java/org/zalando/planb/provider/JWTIssuer.java
- src/test/java/org/zalando/planb/provider/OIDCCreateTokenIT.java
- src/test/resources/testdata.cql
> Feature/67 "azp" (Authorized Party / client ID) scope

- src/main/java/org/zalando/planb/provider/AuthorizeController.java
- src/main/java/org/zalando/planb/provider/AuthorizeResponse.java
- src/main/java/org/zalando/planb/provider/OIDCController.java
- src/main/java/org/zalando/planb/provider/RestControllerAdvice.java
- src/test/java/org/zalando/planb/provider/AuthorizationCodeGrantFlowIT.java
- src/test/java/org/zalando/planb/provider/realms/CustomerUserRealmIT.java
- src/test/java/org/zalando/planb/provider/realms/UpstreamUserRealmTest.java
- now propagating UserRealmAuthenticationException in case of mediatype=application/json
- reformatted using intellij's default
- code duplication refactor
- removed unnecessary imports
- added lombok builder to AuthorizeResponse
- replaced SLF4J Logger instantiation for lombok's @Slf4j
> Issue-76: Upon invalid_grant on mediatype=application/json, return 4XX instead of 200.

- src/main/java/org/zalando/planb/provider/CassandraHealthIndicator.java
- src/main/java/org/zalando/planb/provider/CassandraProperties.java
- src/test/java/org/zalando/planb/provider/HealthCheckIT.java
- src/test/resources/config/application-it.yml
> 70 cassandra health indicator

- src/main/java/org/zalando/planb/provider/ConsentController.java
@hjacobs saw your comment too late :P
> #89: use slf4j

- README.rst
- setup-dev-cassandra.sh
Created this script because the manual process was taking too long if repeated.
Maybe you find it useful.
> Script to setup dev cassandra with sample data

- pom.xml
https://search.maven.org/#search%7Cga%7C1%7Ca%3A%22nimbus-jose-jwt%22
> Updated nimbus-jose-jwt to latest version

- src/main/java/org/zalando/planb/provider/AuthorizeController.java
- src/test/java/org/zalando/planb/provider/ImplicitGrantFlowIT.java
changed reponse url from query to fragment parameters
> fixes #105

- schema.cql
- src/main/java/org/zalando/planb/provider/AuthorizeController.java
- src/main/java/org/zalando/planb/provider/AuthorizeResponse.java
- src/main/java/org/zalando/planb/provider/ClientData.java
- src/main/java/org/zalando/planb/provider/realms/CassandraClientRealm.java
- src/main/resources/api/plan-b-api.yml
- src/main/resources/templates/consent.html
- src/test/resources/testdata.cql
> 96 client meta infos

- src/main/java/org/zalando/planb/provider/RestControllerAdvice.java
- src/test/java/org/zalando/planb/provider/ExceptionHandlingIT.java
- src/test/java/org/zalando/planb/provider/ExceptionHandlingITController.java
- Handle HttpRequestMethodNotSupportedExpection
- Added test case
> #98: Do not log http client mistakes on error level

- Dockerfile
> use latest Docker OpenJDK base image

- Dockerfile
As usual, update of the base docker image to keep up with the latest security patches
> Update base docker image to 8-30

- setup-dev-cassandra.sh
- src/main/java/org/zalando/planb/provider/AuthorizeController.java
- src/main/java/org/zalando/planb/provider/realms/CustomerRealmWebService.java
- src/main/java/org/zalando/planb/provider/realms/GuestCustomerResponse.java
- src/main/java/org/zalando/planb/provider/realms/GuestCustomerUserRealm.java
- src/main/resources/config/application.yml
- src/test/java/org/zalando/planb/provider/realms/GuestCustomerUserRealmIT.java
Details can be found on Zalando TechJIRA: CAS-1644
Post deploy steps include configuring "/guest-customers" realm in provider.keypair.realms and a new client configuration.
> Guest customer

- Dockerfile
> Update to latest OpenJDK

- Dockerfile
> update openjdk base image

- Dockerfile
> upgrade openjdk
